# Generated by Django 3.2.11 on 2022-04-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetail',
            table='userdetail',
        ),
    ]
